### ISSUE TITLE
Move tables to faster table library 

### ISSUE THREAD

**Issue by pburnsdata** [SafetyGraphics/safetyProfile#39]
Reactable is a good starting choice since it's functionality-rich, but thinking maybe down the road moving to faster library. Reactable render is pretty slow when you have any considerable growth in cols or rows. DT for example would be faster, but requires more HTML love

**Comment by samussiah** [comment]
Reactable is maddeningly slow.

**Comment by pburnsdata** [comment]
Yeah every time we've made an interactive table at my current job with reactable we've had to replace it haha literally has not survived anything - even when we are using it for individual patients (always too many visits or params)
