### ISSUE TITLE
Develop approach to study timing.

### ISSUE THREAD

**Issue by samussiah** [SafetyGraphics/safetyProfile#4]
- ADaM: unneeded - study timing is already derived.
- SDTM: relatively straightforward:
  - Reference date: `DM.RFSTDTC`.
  - Domain date: `domain.__DT`, `domain.__STDT`, `domain.__ENDT`, etc.
  - Call function that calculates number of days from reference date.
- EDC:
  - Specify reference date and domain.
  - Specify domain date(s).
  - Call function that calculates number of days from reference date.

**Comment by jwildfire** [comment]
Duplicates #5
